---
name: Auth Service

on:
  push:
    branches:
    - dev
    - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - run: node util/ref-parser.js
      env:
        ref: ${{ github.ref }}
    
    - run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u hreeder --password-stdin
        docker build -t image -f auth_service/Dockerfile .

        docker tag image kondogg/auth:dev
        docker push kondogg/auth

  apply:
    name: Apply
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - run: node util/ref-parser.js
      env:
        ref: ${{ github.ref }}

    - name: Set K8s Context
      uses: azure/k8s-set-context@v1
      with:
        method: service-account
        k8s-url: ${{ secrets.K8S_URL }}
        k8s-secret: ${{ secrets.K8S_SA_TOKEN }}

    - name: Deploy Auth Service
      uses: azure/k8s-deploy@v1
      with:
        kubectl-version: "v1.14.8"
        namespace: ${{ env.K8S_NAMESPACE }}
        manifests: auth_service/manifest.yaml
        images: kondogg/auth:dev
